### ISSUE TITLE
Make result paths human readable

### ISSUE THREAD

**Issue by everner** [trendscenter/coinstac#1024]
**Is your feature request related to a problem? Please describe.**
The current result paths are random strings of characters. They're hard to navigate for someone looking for specific results.

**Describe the solution you'd like**
Maybe something along the lines of `consortium/pipeline/run-ddmmyyyy+HHMMSS/user/`. You can stick the random strings on the end of folder names as necessary to keep things from overlapping. Maybe review with Vince first before working on this.

**Describe alternatives you've considered**
None

**Additional context**

**Comment by rssk** [comment]
Closed under #1064
