### ISSUE TITLE
Computation status dashboard

### ISSUE THREAD

**Issue by swashcap** [trendscenter/coinstac#107]
Feedback from a demo reveals that a computation’s status isn’t immediately visible.

* The “Run Computation” button in the project list view: what is it doing? Not clear.
* Consortium members won’t be video chatting, as developers often are while demoing. The members will need high visibility of computation state through the UI.
* Owners (and perhaps members?) should know who’s ready to run a computation, the number of sites contributing, the current number of iterations, the current meaningful computation output, etc.

(Maybe related to #97.)

**Comment by rssk** [comment]
1/4/2017:

show current iteration status on who we're waiting back from
show who has participated, maybe after the first iteration?

**Comment by swashcap** [comment]
6eedd8e4cce00b1ed1a197b7f9c881ce31c2c297 and cd40ccd516106daf6e092e8b72aeaa41290bf891 added this feature’s core functionality. Will open new PRs/issues addressing enhancements and bugs.
