### ISSUE TITLE
Parse researchers’ files & data

### ISSUE THREAD

**Issue by swashcap** [trendscenter/coinstac#118]
Ensure it’s painless for users to get their data into our application. Our target demo group doesn’t have their files in a single directory, as we’ve assumed: imaging and parsing software often dumps files into multiple, nested directories. Write a file parser that consumes common file structures and data.

* Files’ names aren't unique: we need full directory pathnames to be the keys.
* Always use subject identifier as the unique identifier, **not** the filenames.
* Other software allows a directory search by string for filename in a directory recursively. Can we have globbing and filtering?
* Most people have a standard way of naming things (ex: “SWC1–...” filename). Can we extrapolate from an example file structure?
* FreeSurfer software appears to always add “aseg_stats” to the filename. Should we hard-code this in our parser?
* Filenames **must** exist in the metadata CSV. But they must be unique! Should we change this requirement?
* One file per subject is a reasonable assumption.

**Comment by rssk** [comment]
Vince may not think this is entirely necessary for the Demo, but if its not super hard, it would be worth.

Edit: This decision has been reversed, this is now higher priority

**Comment by swashcap** [comment]
The focus of this issue is changing based on our discussion on 2017-01-30. Based on our conversation, we’ll expect a _single input CSV_ from users. It should look like:

```csv
Filename,Covariate1,Covariate2
/full/path/to/my/file_001_aseg.txt,1,0.551
/full/path/to/my/file_002_aseg.txt,1,0.551
/full/path/to/my/file_003_aseg.txt,1,0.551
/full/path/to/my/file_004_aseg.txt,1,0.551
```

…and so on.

**Comment by sergeyplis** [comment]
Note that this goes well with the modular approach. The code that you will develop will continue to expect the CSV, we will just append a parser (or parser**s** for different situations) that creates that CSV; later we will create GUI to interface with that parser. 

Note, the situations that could simplify researchers' lives could be the following:
 1. Each file contains a key to what group that file (subject) belongs to
 2. Different groups are placed in different directories and it is enough to know what directory the aseg file is located in to assign the group label to it
 3. There is a separate mapping file for the subjects (that is the ideal case)

**Comment by swashcap** [comment]
Per our 2017-01-31 conversation we’ll distribute a “golden set” of data with COINSTAC as zipped up files. We should discuss strategies for file paths.
