### ISSUE TITLE
Sim: revise interface and usability

### ISSUE THREAD

**Issue by rssk** [trendscenter/coinstac#1324]
## Task Description
Sim uses `blessed` (or used to) and `inquierer` to get user input and display results, however blessed is really overkill and often gets in the way of what we really want to display.

So
* change out both libs to just use https://www.npmjs.com/package/terminal-kit
* figure out a sane way to display current computation information, and maybe log output (maybe like trailing output? or if theres a scrolling text box in term kit)
* maybe grab the cpu stats for containers, this is best done inside `coinstac-manager`
* other useful state information?

**Comment by dylanmartin** [comment]
The image download stream could certainly be prettier
![image](https://user-images.githubusercontent.com/7193853/184690477-1d205f08-21a0-4c42-bf23-345a36678ea2.png)
