### ISSUE TITLE
Investigate “Delete User Data” functionality

### ISSUE THREAD

**Issue by swashcap** [trendscenter/coinstac#213]
Clicking the “Delete User Data” button _may_ not work. This one:

![delete-me](https://cloud.githubusercontent.com/assets/1858316/25721578/c7df6b18-30c5-11e7-945e-8bbd3c6aef16.jpg)

Investigate, ensuring that the user is logged out after the button is clicked. A user should be able to log in and resume COINSTAC work.

**Comment by rssk** [comment]
More info: this doesn't work on windows do to how the OS handles files*..... not sure on solution

* Results in EBUSY
