### ISSUE TITLE
Leaving consortia in Windows is buggy

### ISSUE THREAD

**Issue by bmiller0919** [trendscenter/coinstac#229]
Windows 10 machine:
I left a consortium and this removed all my results from the Home page even for consortia I didn't leave. We ran another computation for a different consortium and the results never appeared on the Home page either and I keep getting empty notifications on the Home page (see attached). Logging out and back in seemed to resolve the issue and results reappeared.

Windows 7:
I left a consortium and the page froze and went white after a while. I exited the application and logged back in. When back it it still said I was part of the consortium. I tried to leave again and then it exhibited the behavior noted above for Windows 10.  Logging out and back in also resolved the issue. 

![pasted image at 2017_06_15 02_46 pm](https://user-images.githubusercontent.com/7771196/27202229-ffe24484-51dd-11e7-9470-bebd5d06caed.png)

**Comment by rssk** [comment]
The issue here is that there is a dead DB in the status page is trying to access, this crashing the comp result prom.

Another issue I observed, I couldn't 'Log Out' the page hung indefinitely, I'm guessing another DB issue....

**Comment by bmiller0919** [comment]
I have also had the log out issue, but I thought it was a known bug for some reason. Sorry I didn't mention it!

**Comment by swashcap** [comment]
> I couldn't 'Log Out' the page hung indefinitely

I recall this sounds like an Electron 1.6+ issue. #232 ~should~ _will_ revert us back to 1.5.1.
