### ISSUE TITLE
Application Icon doesn't appear in Windows 10

### ISSUE THREAD

**Issue by bmiller0919** [trendscenter/coinstac#230]
The icon for the app appears to be the default app icon in Windows 10. Windows 7 displays the icon correctly.  
![coinstacicon](https://user-images.githubusercontent.com/7771196/27202950-e2a93cee-51e0-11e7-815f-423a0ca8461e.PNG)

**Comment by swashcap** [comment]
Atom on Windows 10 seems totally fine:

![atom-is-fine](https://user-images.githubusercontent.com/1858316/27310943-6eda96ca-5512-11e7-9cdc-fb3eeaec8f77.jpg)

_Might_ be an issue with our icon being to small. Trying a new, 256 × 256px version.
