### ISSUE TITLE
Editing My Files if consortium is changed doesn't work on Windows 10

### ISSUE THREAD

**Issue by bmiller0919** [trendscenter/coinstac#231]
Jing started a single shot consortium and we ran it with her computer and the two Windows machines. Jing then updated the single shot consortium to be a multishot. I updated the covariate mapping on the same files used for the single shot on the Windows 7 machine just fine, but when I updated the mapping on the W10 machine it would not let me update the mapping and the notification said "Document update conflict".
![documentupdateconflict](https://user-images.githubusercontent.com/7771196/27243369-b945bd0a-529e-11e7-9035-c45d4e286a4f.png)

When I look at that entry on my files it says, "Must remap covariates"

I was able to add the files as a new set and that worked fine.

**Comment by bmiller0919** [comment]
Gots new info. I don't think this is related to anything mentioned above because this happened last night when I created a new project on both windows 7 and 10 machines. I labeled the project `06252017` on both and both threw the same error reported. Maybe it has to do with the title being all digits??

**Comment by swashcap** [comment]
Interesting. #228 allows single-digit “Files Collection” names, so I’m not sure it’s number related. I’ll try to check it out today.

**Comment by bmiller0919** [comment]
Sounds good. In this case I simply changed the name to `new` for both and it created the new file entry just fine.

**Comment by swashcap** [comment]
_Interesting_. Wonder if we're filtering/mapping files collections somewhere and the all-numbers name somehow breaks filtering.
