### ISSUE TITLE
Intergration: new Coinstac Server

### ISSUE THREAD

**Issue by rssk** [trendscenter/coinstac#349]
# Problem
The architecture of coinstac-server has changed drastically, formerly `coinstac-server-core`, and needs to be redesigned.

# Solution
What does the new server need to do? For basic integration it needs to start pipelines and save their results, possibly make the updating state information available (iteration, etc...), and also optionally; auth.

So
* make a hapi server
* make a route to start the pipeline, this will be from the graphql->rethink/graph api server-> hapi api
* Make the dbmanager, for now that'll just be a library (in the same package/coinstac-server dir) that allows the hapi server to save to the database (should this go through graphql? I dont think so but not 100)
* Make another dbmanager func to save updating state data
* Make a func to allow the pipeline to get a JWT

**Comment by tkah** [comment]
Resolved in PR #360
