### ISSUE TITLE
Integration: Pipeline in the Client

### ISSUE THREAD

**Issue by rssk** [trendscenter/coinstac#350]
# Problem
The client no longer can use the same pipeline code

# Solution
Put the new pipeline code into the client. The pipeline should be started when each user finished their data mappings, though the owner will start the remote first. The local pipeline state data can be used to show UI updates, as well as the remote data which will come from a rethink stream. At the moment there is no stoping or pausing pipelines, but that will be a future feature.

**Comment by tkah** [comment]
Resolved in PR #360
