### ISSUE TITLE
UI: runs visible to past consort members

### ISSUE THREAD

**Issue by rssk** [trendscenter/coinstac#464]
# Problem
interesting bug:
* built a new app on windows, never been run
* login as test2
* test2 _was_ a member of `test consort 2` but is no longer
* can see runs on home page from that consort
my _guess_ is that that ID is still in the run doc, thus giving view perms?
when it needs to check the actual consort table

# Tasks
* make runs not visible :-)

**Comment by tkah** [comment]
Closed by commit #362d9da
