### ISSUE TITLE
UI: VBM and MSR Integration

### ISSUE THREAD

**Issue by tkah** [trendscenter/coinstac#476]
# Problem
* VBM and MSR are ready for integration into the UI.
# Tasks
* Do it

**Comment by hvgazula** [comment]
The following repos contain VBM related code that are ready for integration into the UI
https://github.com/MRN-Code/coinstac_ssr_vbm_mcic
https://github.com/MRN-Code/coinstac_drne_vbm_mcic

**Comment by hvgazula** [comment]
The following repo contains multi-shot regression with multiple regressions on the MCIC data (please not that this code is not yet optimized) and is ready for integration into the COINSTAC UI

https://github.com/MRN-Code/coinstac_msr_vbm_mcic

**Comment by tkah** [comment]
The MCIC comps are being put on hold for the time being as we look at how to use masking files in COINSTAC.
