### ISSUE TITLE
UI: selection box for freesurfer regions of interest is bonkers

### ISSUE THREAD

**Issue by rssk** [trendscenter/coinstac#505]
# Problem
The selection box is impossibly hard to use to select more than one item, or use at all really.
# Tasks
* fix dat trash

**Comment by pixelsaurus** [comment]
Emailed Jess for feedback on solution. Haven't heard back yet.

**Comment by pixelsaurus** [comment]
Also, add an 'all' selection to run against all regions.

**Comment by pixelsaurus** [comment]
Heard from Jess, she likes the new UI.
