### ISSUE TITLE
UI: Make the results table look like this example

### ISSUE THREAD

**Issue by everner-ds** [trendscenter/coinstac#522]
# Problem
The current regression shows outputs that are not descriptive enough.

# Tasks
Make the output look like the attached image. This is a screenshot of the old COINSTAC output, so it should be in a past version somewhere.
<img width="1280" alt="screen shot 2018-05-11 at 3 23 05 pm" src="https://user-images.githubusercontent.com/17751425/39947580-a4668fce-552f-11e8-86a3-7dceace80b8f.png">

**Comment by hvgazula** [comment]
Updated code at https://github.com/MRN-Code/coinstac_ssr_fsl and https://github.com/MRN-Code/coinstac_drne_fsl

**Comment by hvgazula** [comment]
Corrected a small error in the aforementioned repos. Should be good now.
