### ISSUE TITLE
Ubuntu 16.04: Help doesn't start on Linux

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [trendscenter/coinstac#551]
# Problem
Coinstac is run with *gksudo*. The default web browser is Google Chrome. Google Chrome doesn't like being run as *root*, see attached screen capture.
![chrome](https://user-images.githubusercontent.com/3234522/41358304-633058b0-6f28-11e8-97e8-e5cd44d02a5f.png)
(can provide screen captures in English locale if needed)

# Tasks

**Comment by DimitriPapadopoulos** [comment]
This is easy to reproduce with the Help menu:
- Select `Help` > `Learn More` in the COINSTAC menu.
- COINSTAC attempts to launch a browser. The default browser on our Linux machines is Firefox, but for some reason COINSTAC attempts to run Google Chrome - which cannot be launched by a privileged user -unless you add the option `--no-sandbox`.

This means that Help cannot work on Linux.

![learn_more](https://user-images.githubusercontent.com/3234522/49862356-4e2ea380-fdfe-11e8-8c15-84e0f5ca449c.png)
![google_chrome](https://user-images.githubusercontent.com/3234522/49862358-51299400-fdfe-11e8-956b-03aa381d81bf.png)

**Comment by rssk** [comment]
Coinstac linux setup no longer requires `gksudo`, closing
