### ISSUE TITLE
Ubuntu 16.04: cannot access demo data from Coinstac (Wednesday demo on 2018-06-13)

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [trendscenter/coinstac#552]
# Problem
Perhaps related to my configuration:
* the home dir `/home/xxxxxx` of my acccount `xxxxxx` (which is defined in a remote LDAP server) is NFS-mounted from a remote file server:
```
$ df -h $HOME
Filesystem                      Size  Used Avail Use% Mounted on
132.166.143.175:/home/xxxxxx  4.0T  2.0T  2.1T  49% /home/xxxxxx
$ 
```
* Coinstac and sample data are on `/volatile` which is a local disk
* of course `/root`and `/var/lib/docker` are on a local disk as well
```
$ df -h /volatile /root /var/lib/docker
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda6       426G  111G  294G  28% /volatile
/dev/sda1        29G   22G  4.8G  83% /
/dev/sda1        29G   22G  4.8G  83% /
$ 
```

The `root` account has access to all local disks of course, including `/volatile`, `/root`and `/var/lib/docker`, but *not* `/home/xxxxxx`. Does anything useful happen on `/home/xxxxxx`?

# Tasks

**Comment by DimitriPapadopoulos** [comment]
Interesting messages from the system log `/var/log/syslog`?
```
Jun 13 16:21:49 is223528 dockerd[2361]: time="2018-06-13T16:21:49.672799563+02:00" level=warning msg="Couldn't run auplink before unmount /var/lib/docker/aufs/mnt/565016dfd510e84b4c818753d803c1f24ee6e68bef4b479075bb7524f5396fbd-init: exec: \"auplink\": executable file not found in $PATH"
Jun 13 16:21:49 is223528 kernel: [ 6082.616524] aufs au_opts_verify:1597:dockerd[2771]: dirperm1 breaks the protection by the permission bits on the lower branch
Jun 13 16:21:49 is223528 kernel: [ 6082.651129] aufs au_opts_verify:1597:dockerd[2771]: dirperm1 breaks the protection by the permission bits on the lower branch
Jun 13 16:21:49 is223528 dockerd[2361]: time="2018-06-13T16:21:49.706031788+02:00" level=warning msg="Couldn't run auplink before unmount /var/lib/docker/aufs/mnt/565016dfd510e84b4c818753d803c1f24ee6e68bef4b479075bb7524f5396fbd: exec: \"auplink\": executable file not found in $PATH"
Jun 13 16:21:49 is223528 kernel: [ 6082.688294] aufs au_opts_verify:1597:dockerd[2808]: dirperm1 breaks the protection by the permission bits on the lower branch
```

**Comment by DimitriPapadopoulos** [comment]
See for example docker-library/docker#25.

Does this mean I definitely need a more recent version of Docker, so remove the version shipped with Ubuntu 16.04 LTS (1.13.1, build 092cba3) and install the latest Docker CE instead?

That would be a pity - means Docker is as much portable as Java :-(

**Comment by DimitriPapadopoulos** [comment]
I have just installed _auplink_ on my Ubuntu 16.04 workstation:
```
sudo apt install aufs-tools
```
Not sure what _auplink_ does but it would be interesting to run another test and see how it goes...

**Comment by rssk** [comment]
Home directory location selection and network volume mount option for pipeline should solve these issues, closing
