### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [trendscenter/coinstac#555]
# Problem

The [top-level README](https://github.com/MRN-Code/coinstac/blob/master/README.md) file states:
> ## License
> MIT. See [LICENSE](./LICENSE) for details.

The link does not work, there is no top-level LICENSE file. A LICENSE files is also missing from some subdirectories such as [`packages/coinstac-api-server`](https://github.com/MRN-Code/coinstac/tree/master/packages/coinstac-api-server).

# Tasks

Options:
* Add a LICENSE file in the [top-level directory of MRN-Code/coinstac](https://github.com/MRN-Code/coinstac), remove LICENSE file from subdirectories, and link to this single top-level LICENSE file from all README files in subdirectories.
* Remove the reference to a LICENSE file in the top-level README and add missing LICENSE files in subdirectories.

Which one do you prefer?

**Comment by rssk** [comment]
This is now working:-), closing
