### ISSUE TITLE
Packages fail to build with Node.js 10

### ISSUE THREAD

**Issue by swashcap** [trendscenter/coinstac#598]
# Problem

Packages fail to build with Node.js 10.12.0. Specifically, I've tracked this down to sqlite3, which is a dependency of [spawn-pouchdb-server](https://github.com/gr2m/spawn-pouchdb-server), which we use for tests in coinstac-common.

# Tasks

spawn-pouchdb-server hasn't been updated in 1.5 years. We only rely on it [for runner pool testing](https://github.com/MRN-Code/coinstac/blob/master/packages/coinstac-common/test/models/pipeline/runner/pool/.test-pool-utils.js#L19), so we could feasibly replace its use with [pouchdb-server](https://github.com/pouchdb/pouchdb-server), which _should_ work with recent versions of Node.js.

Otherwise, we could open a PR to spawn-pouchdb-server and wait for a new version.

**Comment by swashcap** [comment]
Oh, and spawn-pouchdb-server's tests fail on `master`. So…

**Comment by rssk** [comment]
that code is all ded, so it just needs to be gutted, good lookin out

**Comment by rssk** [comment]
Closing due to deprecated code
