### ISSUE TITLE
Can't run DRNE Freesurfer on Ubuntu

### ISSUE THREAD

**Issue by everner-ds** [trendscenter/coinstac#618]
# Problem

Pipeline run doesn't complete (or even seem to start) when running DRNE Freesurfer with one user on Ubuntu. Tried running both by clicking coinstac file in file manager and by typing `gksudo coinstac` from terminal. Screenshots and logs are attached.

[gksudo-error-out.txt](https://github.com/MRN-Code/coinstac/files/2617784/gksudo-error-out.txt)
![coinstac-docker-error-screenshot](https://user-images.githubusercontent.com/17751425/49049894-328c9180-f19e-11e8-85cd-844d0d94f3a6.png)
[coinstac-dev-tools-console-error.log](https://github.com/MRN-Code/coinstac/files/2617785/coinstac-dev-tools-console-error.log)
[coinstac-logs.txt](https://github.com/MRN-Code/coinstac/files/2617792/coinstac-logs.txt)

# Tasks
Make COINSTAC work with Ubuntu 16.04.

**Comment by everner-ds** [comment]
I reopened COINSTAC with gksudo and tried downloading the DRNE Freesurfer image again. The application did not crash. I tried running the pipeline again and got this error.

<img width="594" alt="screen shot 2018-11-26 at 5 36 10 pm" src="https://user-images.githubusercontent.com/17751425/49051040-5a322880-f1a3-11e8-921c-111efb91d3d0.png">

**Comment by everner-ds** [comment]
I tried running the same pipeline on Mac and got the same error. Seems to be a problem with the remote server. I think it would make sense to do some kind of continual health checks and monitoring on the remote server so we know when it's not working.

Additionally, it would be good if this 504 error was bubbled up to the user so that they knew there was a problem with the remote.

Another idea is that the client could ping the remote server and see if it's healthy before starting a pipeline run.

**Comment by everner-ds** [comment]
After Ross restarted the remote, I still get the same error on my Mac. However, this time, the pipeline returns an error and stops.

<img width="941" alt="screen shot 2018-11-27 at 3 34 19 pm" src="https://user-images.githubusercontent.com/17751425/49116181-0e8e8600-f25a-11e8-8d2c-fbac28758a9c.png">

When I click on View Error, I get this:

<img width="943" alt="screen shot 2018-11-27 at 3 36 09 pm" src="https://user-images.githubusercontent.com/17751425/49116260-43024200-f25a-11e8-8364-5dea26d4ed33.png">

Ross thinks it's an MRN IT issue.

**Comment by rssk** [comment]
CNR
