### ISSUE TITLE
"Forgot Password" doesn't work

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [trendscenter/coinstac#626]
# Problem
Nothing happens when clicking on the `Forgot Password?` in COINSTAC.

## Is this an App issue?
To submit an issue please
* put the log dumps as a gist
    * Actually log files cannot be found, probably because the `HOME` directory is hosted on an NFS filer and root does not have access to the filer:
    ```$ ls -ld ~/.config/coinstac
    ls: cannot access '/home/user/.config/coinstac': No such file or directory
    $ ```
* screen shots when relevant
![forgot_password](https://user-images.githubusercontent.com/3234522/49862680-ff353e00-fdfe-11e8-8873-f1c9b8968247.png)

# Tasks

**Comment by rssk** [comment]
Thanks Dimitri for the thorough info! This is a known issue at the moment, that we hope to have resolved in the future.
