### ISSUE TITLE
Users cannot join consortia

### ISSUE THREAD

**Issue by everner-ds** [trendscenter/coinstac#631]
# Problem
Users cannot join consortia created by others. Nothing happens in the UI when a user clicks Join Consortium. 

## Is this an App issue?
Yes, app issue.

[Gist of COINSTAC log dumps from Dec 14.](https://gist.github.com/everner-ds/a41ad0289b3110f9d8605d0536b64bc4)

# Tasks
Fix this bug.

**Comment by everner-ds** [comment]
Error from Electron dev console

<img width="593" alt="screen shot 2018-12-14 at 6 31 23 am" src="https://user-images.githubusercontent.com/17751425/50015731-76480f00-ff84-11e8-951f-234d44a94f9c.png">

**Comment by rochaeb** [comment]
I wasn't able to reproduce this one. Maybe it was because the "Join Consortium" button only shows up when the consortium has an active pipeline.
