### ISSUE TITLE
Touch up UI

### ISSUE THREAD

**Issue by everner** [trendscenter/coinstac#649]
# Problem

The UI could use some polishing in a few places. I notice that half the logo is cut off. Additionally, the fonts change a lot within a page for no apparent reason, which looks weird.

# Tasks

Fix UI aesthetic issues.

**Comment by everner-ds** [comment]
The isControl "button" is overlapping the border of its container. Additionally, half the logo is cut off.

![screen shot 2019-02-19 at 5 49 12 pm](https://user-images.githubusercontent.com/17751425/53058344-e638b100-346f-11e9-8834-0aa1d7b26b0b.png)

Covariates is a different front than Start and End dates. Additionally, font for DOF and R^2 values is different from font of other numbers on the page.
![screen shot 2019-02-19 at 5 50 47 pm](https://user-images.githubusercontent.com/17751425/53058355-efc21900-346f-11e9-9e16-2f25ac8d75de.png)

**Comment by everner-ds** [comment]
The screens feel cramped sometimes. Might be better to reduce the font size?
