### ISSUE TITLE
cache, output and transfer folders are not cleaned when a computation starts

### ISSUE THREAD

**Issue by hvgazula** [trendscenter/coinstac#674]
# Problem
cache, output and transfer folders are not empty/cleaned when a computation starts

# Tasks
would be nice to start clean

**Comment by rssk** [comment]
by design, it should clean everything on end, excluding output. So, it shouldn't need to clean on startup.... But I'll make sure of that

Output is trickier, as we are storing data there in UI version, I can maybe add a flag that cleans everything for sim though

**Comment by rssk** [comment]
Coinstac system used dirs are cleaned out, but output isnt on sim for now, if this comes up again we can revisit
