### ISSUE TITLE
files are not deleted when moved from client transferDirectory to remote

### ISSUE THREAD

**Issue by hvgazula** [trendscenter/coinstac#675]
# Problem
## Is this an App issue? 
I don't know if this is an app issue

# Tasks
It doesn't do what the documentation suggests

**Comment by hvgazula** [comment]
Okay, I see the files (inside each client transfer folder) being deleted at the end when the docker box shuts down. hmm...interesting that they are deleted at the end instead of being deleted when that local computation finishes.

**Comment by rssk** [comment]
this should be deleting with every transfer, I'll look into it

**Comment by rssk** [comment]
CNR
