### ISSUE TITLE
VBM Regression on 2 mm files fails

### ISSUE THREAD

**Issue by hvgazula** [trendscenter/coinstac#677]
# Problem
https://github.com/trendscenter/coinstac-regression-vbm
<img width="1440" alt="Screen Shot 2019-06-24 at 3 26 49 PM" src="https://user-images.githubusercontent.com/9400767/60046098-81e36380-9694-11e9-96fa-0674bde8dc29.png">

# Tasks

**Comment by rssk** [comment]
Issue was with excessive docker memory consumption, it'd be nice to have a better error, but unfortunately I'm not sure there is an easy solution
