### ISSUE TITLE
Version mismatch in Coinstac app

### ISSUE THREAD

**Issue by hvgazula** [trendscenter/coinstac#678]
# Problem
Please check the 'version' file in coinstac-darwin-x64
<img width="1440" alt="Screen Shot 2019-07-06 at 11 24 35 PM" src="https://user-images.githubusercontent.com/9400767/60763566-3db57300-a045-11e9-97dc-78de13be8da6.png">

## Is this an App issue?
To submit an issue please
* put the log dumps as a gist
    * log files can be found here:
    ```// these are appended to the home dir for you OS
  // *nix: ~/.config/coinstac
  // win: C:\Users\username\AppData\Local\Temp\coinstac
  logLocations: {
    darwin: 'Library/Logs/coinstac/',
    freebsd: '.config/coinstac/',
    linux: '.config/coinstac/',
    sunos: '.config/coinstac/',
    win32: 'coinstac/',
* copy any relevant errors in the electron dev console
* copy any relevant logs from docker
    * dockers logs can be found using `docker logs ContainerID`
    `docker ps -a` will show all recent containers
* screen shots when relevant

# Tasks

**Comment by rssk** [comment]
This is confusing, but that version is the Election binary version, not the Coinstac version
