### ISSUE TITLE
Nice to Have: A way to recognize the primary local node (the one who enters info in the UI)

### ISSUE THREAD

**Issue by hvgazula** [trendscenter/coinstac#688]
It would be nice to identify this user without the need for having another field on the UI. Spoke to @rssk about this.

**Comment by hvgazula** [comment]
@pixelsaurus Do you have any update on this?

**Comment by pixelsaurus** [comment]
Yes. Let's chat tomorrow sometime.

**Comment by rssk** [comment]
`owner` field now exists in the pipeline state
