### ISSUE TITLE
Add description of the step to the pipeline progress display

### ISSUE THREAD

**Issue by everner** [trendscenter/coinstac#692]
# Problem
Users don't know what the current step/iteration is doing in a multistep computation.

## Is this an App issue?
Both app and computation issue.

# Tasks
Show a description of what the computation is doing at each step/iteration to the user on the pipeline display page. This will need to be created by the computation creators as part of the computation. It could be a table with that the app can ingest before the pipeline run, or it can be something that's outputted by the computation on each step; whatever is easiest to program is fine at this point.

**Comment by rssk** [comment]
The whole pipeline state information display needs to be rewritten and made more user friendly, changing priority
