### ISSUE TITLE
Saving an already created pipeline is broken

### ISSUE THREAD

**Issue by rssk** [trendscenter/coinstac#698]
# Task

* When a pipeline has been saved, it should be able to be edited, instead it sometimes appears greyed out

* find out why its greyed out

* Correct functionality is:
  - the pipeline should always be editable
  - when the pipeline is set to active on the consortia pipeline page, editing the pipeline
     should un-map the current users who are mapped to the pipeline. This is already done if the 
     active pipeline is switched on the consortia pipeline page, look how this is done 

Perhaps relevant error:

Error:
collections.js:421 Uncaught (in promise) TypeError: col.associatedConsortia.indexOf is not a function
    at eval (collections.js:421)
    at Array.forEach (<anonymous>)
    at eval (collections.js:420)
    at Promise.js:801
    at callListener (Promise.js:469)
    at endMicroTickScope (Promise.js:555)
    at IDBTransaction.<anonymous> (Promise.js:624)

**Comment by kalitopix** [comment]
hi, @rssk 
I checked the codebase and found out what makes the inputs grey.
All inputs are disabled if runId in params is provided to this component.
What is rundId and what is this for?

Also, it seems that only allow pipeline editing for its creator.
But I could not find creator/owner field in the database.
