### ISSUE TITLE
On Maps page, change "First Row" to "Header"

### ISSUE THREAD

**Issue by everner** [trendscenter/coinstac#721]
# Tasks

The first row of a CSV is typically called a "header." On the Maps page, after a files group has been added, please replace "First Row" with "Header."

<img width="743" alt="Screen Shot 2019-09-06 at 11 07 08 AM" src="https://user-images.githubusercontent.com/2123095/64438661-7c43ca00-d096-11e9-9287-1eab7124a3bd.png">

**Comment by pixelsaurus** [comment]
Closed with PR #741
