### ISSUE TITLE
Is there a need for these files and images?

### ISSUE THREAD

**Issue by hvgazula** [trendscenter/coinstac#724]
https://github.com/MRN-Code/coinstac/blob/master/packages/coinstac-api-server/test/data/coinstac-decentralized-test.json

https://github.com/MRN-Code/coinstac/blob/master/packages/coinstac-api-server/test/data/coinstac-decentralized-error.json

https://github.com/MRN-Code/coinstac/blob/master/packages/coinstac-api-server/test/data/coinstac-local-error.json

https://github.com/MRN-Code/coinstac/blob/master/packages/coinstac-api-server/test/data/coinstac-local-test.json

**Comment by hvgazula** [comment]
Either point them to the right repos or just delete them.

**Comment by hvgazula** [comment]
@rssk Can you please answer this question?

**Comment by rssk** [comment]
yes, theyre for internal testing
