### ISSUE TITLE
PDF files are larger than they should be

### ISSUE THREAD

**Issue by everner** [trendscenter/coinstac#748]
# Problem
PDF files produced by VBM analysis with GIGA are ~100 MB. However, the constituent PNG files are about 500 kB total, and the PDF can be zipped to around 1-2 MB. Large file sizes make sharing PDFs difficult.

# Tasks
Make PDF files smaller so that they can easily be emailed. Shoot for around 1 MB.

**Comment by pixelsaurus** [comment]
Closed with PR #750
