### ISSUE TITLE
Invite-only consortia

### ISSUE THREAD

**Issue by everner** [trendscenter/coinstac#779]
Can we have an option for the consortium owner to make the consortium “invite-only?” This will be necessary for analyses we have planned with sensitive data sets. I imagine it would be a checkbox on the Consortium Create page. If checked, then the JOIN CONSORTIUM button would not appear in the card for that consortium on the Consortium List page. Other users could only be added to the consortium by the owner.

**Comment by pixelsaurus** [comment]
Eduardo has a PR in for this.
