### ISSUE TITLE
"version" file not accurate

### ISSUE THREAD

**Issue by everner** [trendscenter/coinstac#803]
# Problem
In the app build for Mac, there is a file named "version" that I assume is supposed to be the current COINSTAC version. The one that came with COINSTAC v4.6.2 says 4.2.12 inside. Not a huge deal, but we should keep these up to date, hopefully by automatically generating them during the build process. 

# Tasks
Make sure version file has current version. 
Bonus: automatically generate the file during the build process.

**Comment by rssk** [comment]
File is version for electron
