### ISSUE TITLE
Fix descriptions on fMRI preprocessing and VBM

### ISSUE THREAD

**Issue by everner** [trendscenter/coinstac#806]
# Problem
It looks like the description for VBM was accidentally put on fMRI preprocess. 

<img width="1246" alt="Screen Shot 2020-01-23 at 9 35 56 AM" src="https://user-images.githubusercontent.com/2123095/72993725-e057f800-3dc3-11ea-8d58-9a017803dcc5.png">

# Tasks
Please make the following changes:

1. Put the current description of fMRI preprocess onto VBM.

"This computation runs Voxel Based Morphometry on structural T1 weighted MRI scans(BIDS format and T1w nifiti) using SPMv12 standalone and MATLAB Runtimev713. Each scan takes approximately 5 mins to run on a system with 2.3 GHz,i5 equivalent processor, 8GB RAM. Each scan output directory takes about 150MB space. Please make sure to have the space and resources."

2. Put this description onto fMRI preprocess:

"This computation performs realignment, slice timing, normalization, and smoothing on functional T2*-weighted MRI scans (BIDS format and nifiti) using SPMv12 standalone and MATLAB Runtimev713."

**Comment by hvgazula** [comment]
Not really accidental. It comes from the description key under meta in compspec.json. See [here](https://github.com/trendscenter/Coinstac_fmri_computation/blob/master/compspec.json#L7). The repo maintainer has to change the description there. Or please feel free to update the compspec yourself if you have time.

**Comment by rssk** [comment]
Closed by #808
