### ISSUE TITLE
UI - MSR Freesurfer Results Crashing

### ISSUE THREAD

**Issue by pixelsaurus** [trendscenter/coinstac#874]
# Problem

Using COINSTAC v. 4.7.3 Completed an MSR Freesurfer demo run with an ENIGMA researcher, clicked on the "View Results" button which resulted in a blank screen. 

Here's the console log 

<img width="1280" alt="Screen Shot 2020-04-30 at 10 51 17 AM" src="https://user-images.githubusercontent.com/664834/80737302-8d7f9200-8ad0-11ea-86f9-0c726bbd996f.png">

# Tasks

Investigate and Fix.

**Comment by rssk** [comment]
Fixed by #884
