### ISSUE TITLE
"Copyright (c) 2013-2018 GitHub Inc." of the downloaded releases

### ISSUE THREAD

**Issue by yarikoptic** [trendscenter/coinstac#876]
I have downloaded coinstac-linux-x64 for a release or linux from https://github.com/trendscenter/coinstac/releases . LICENSE shipped within it states

Copyright (c) 2013-2018 GitHub Inc.

which is likely to be incorrect

**Comment by rssk** [comment]
Hey @yarikoptic! This is the license file for Electron which our build tool is placing automatically, I was under the impression that it was using the license in the build root but that does not appear to be the case. It seems like the best solution is place our license and include but rename the Electron license as required by their license
