### ISSUE TITLE
Please setup a CI with github integration (pull requests, etc)

### ISSUE THREAD

**Issue by yarikoptic** [trendscenter/coinstac#878]
In the light of #877 I had decided to pick into a CI setup I expected to find in the repository as to discover what are the dependencies necessary to run coinstac.  But I found no trace of any CI (travis, circle, github actions) setup neither in the code, nor in badges in README.md; nor in status reports for the pull requests.

**Comment by rssk** [comment]
We have just gotten access to a CircleCI account and have planned to add CI integration pending our database rewrite here #859
