### ISSUE TITLE
UI - Fix User Formatting on Run Activity Panel

### ISSUE THREAD

**Issue by pixelsaurus** [trendscenter/coinstac#942]
<img width="670" alt="Screen Shot 2020-08-14 at 10 38 41 AM" src="https://user-images.githubusercontent.com/664834/90272403-9c3d4b00-de1a-11ea-818c-8dce84b0d8f8.png">

Remove trailing comma and add space between comma after user and next user.

**Comment by rssk** [comment]
Fixed?
