### ISSUE TITLE
UI - Logs page length can interfere with navigation

### ISSUE THREAD

**Issue by pixelsaurus** [trendscenter/coinstac#946]
If the logs on the Logs page get too lengthy, it can take a while to scroll back to the top to navigate elsewhere. 

I propose wrapping the logs in a <div> with a minimum height and the style set to overflow-y: auto (or similar) so that one can scroll within the pane, but the navigation is visible as the page length never changes.

**Comment by rssk** [comment]
there are up and down arrows to now deal w/ this, closing
