### ISSUE TITLE
Cannot map for DP SVM

### ISSUE THREAD

**Issue by everner** [trendscenter/coinstac#959]
**Describe the bug**
The screen goes blank when I click MAP LOCAL DATA on the Consortia page.

**To Reproduce**
1. Create a consortium with DP SVM as the pipeline
2. Click on Consortia
3. Click on MAP LOCAL DATA on that consortium

**Expected behavior**
Go to the page where I can map my data.

**Desktop (please complete the following information):**
 - OS: OSX 10.14.6
 - Version 4.7.5

**Additional context**
Log not very helpful:
`{"message":"process: render - \"Unhandled error: [object ErrorEvent]\"","level":"error"}`
Here is the error from the Dev Tools:
<img width="1172" alt="Screen Shot 2020-09-03 at 16 58 40" src="https://user-images.githubusercontent.com/2123095/92166550-c88b2c80-ee06-11ea-8e6e-f474b1dadfd7.png">

**Comment by rssk** [comment]
Fixed by #847
