### ISSUE TITLE
Cannot run Freesurfer Regression

### ISSUE THREAD

**Issue by everner** [trendscenter/coinstac#960]
**Describe the bug**
When I tried to run Freesurfer Regression, first the pipeline would not start. I clicked on it three times. I checked, and Docker was on but not running anything. Then I closed and reopened COINSTAC and the three pipelines started. However, after 10 minutes, they were still in the first iteration of the local side. They should take a very short amount of time to run. I stopped all three pipelines and restarted COINSTAC again. The three pipelines started up again. I stopped them and started a new one. I saw the same behavior with it. I stopped all four pipelines and restarted COINSTAC. When I reopened the application, I saw that four pipelines open, none of which were making any progress.

**To Reproduce**
1. Create Freesurfer Regression pipeline with 5 ROIs for a single user.
2. Map data.
3. Run pipeline.

**Expected behavior**
I expect the pipeline to complete in a few minutes.

**Desktop (please complete the following information):**
 - OS: OSX 10.14.6
 - Version 4.7.5

**Additional context**
Did not see any errors in the logs.

**Comment by rssk** [comment]
Pipeline run bugs that should be fixed via the listener rewrite, closing
